
<div style="background-color: lightgreen; color: black; padding: 20px; box-sizing: border-box; width: 99%;">

👋 <b>Olá! Eu sou o Dot, seu revisor de IA.</b>

🎉 <b>Parabéns! Você foi aprovado no seu projeto.</b>

Ótimo trabalho ao corrigir os problemas da rodada anterior! Sua conclusão agora relata a acurácia final de teste de 0.8243, os resultados de validação dos três modelos e os melhores hiperparâmetros, e sua busca de modelos está mais ampla e mais bem fundamentada. Em projetos futuros, concentre-se em manter o notebook organizado, executando cada etapa apenas uma vez (o carregamento e a divisão estão repetidos atualmente) e removendo anotações deixadas para trás e artefatos de `[cite]`. Continue com o excelente trabalho!

Se você tiver alguma dificuldade ou erro, fique à vontade para entrar em contato com nossa equipe de suporte clicando no ícone de chat no canto superior direito ou enviando um e-mail para [helpme@tripleten.com](mailto:helpme@tripleten.com).

<hr style="margin-top: 20px; margin-bottom: 20px;">

<details>
<summary><b style="cursor: pointer;">💡 Clique aqui para ver como ler meus comentários (Legenda de cores)</b></summary>
<div style="margin-top: 15px;">
Veja meus comentários abaixo. <b>Peço gentilmente que não os mova, modifique nem exclua</b>.

Você encontrará meus comentários destacados em caixas verdes, amarelas ou vermelhas como estas:

<div class="alert alert-block alert-success">
Sucesso. Tudo foi feito corretamente.
</div>

<div class="alert alert-block alert-warning">
Observações. Algumas recomendações.
</div>

<div class="alert alert-block alert-danger">
A corrigir. O bloco requer algumas correções.
</div>
</div>
</details>

</div>

In [1]:
# 1. Importações das bibliotecas necessárias
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# 2. Carregando os dados
# (Dica: se o arquivo estiver numa pasta datasets, ajuste para 'datasets/users_behavior.csv')
df = pd.read_csv('users_behavior.csv')

# Exibindo as primeiras linhas para confirmar o carregamento
print("Primeiras linhas do DataFrame:")
display(df.head())

# Exibindo informações gerais do dataset (linhas, colunas e tipos)
print("\nInformações do DataFrame:")
df.info()

# 3. Análise Exploratória Inicial e Distribuição da Alvo (Feedback do revisor)
print("\nDistribuição da coluna alvo (is_ultra):")
target_counts = df['is_ultra'].value_counts(normalize=True) * 100
print(f"Plano Smart (0): {target_counts.get(0, 0):.2f}%")
print(f"Plano Ultra (1): {target_counts.get(1, 0):.2f}%")

# 4. Separando os recursos (features) e o alvo (target)
features = df.drop(['is_ultra'], axis=1)
target = df['is_ultra']

# 5. Dividindo os dados (60% treino, 20% validação e 20% teste)
# Separamos primeiro 60% para treino e 40% temporário
features_train, features_temp, target_train, target_temp = train_test_split(
    features, target, test_size=0.4, random_state=54321
)

# Dividimos os 40% temporários igualmente em validação e teste (20% cada)
features_valid, features_test, target_valid, target_test = train_test_split(
    features_temp, target_temp, test_size=0.5, random_state=54321
)

print("\nTamanho dos conjuntos:")
print("Tamanho do conjunto de treino:", len(features_train))
print("Tamanho do conjunto de validação:", len(features_valid))
print("Tamanho do conjunto de teste:", len(features_test))

Primeiras linhas do DataFrame:

   calls  minutes  messages   mb_used  is_ultra
0   40.0   311.90      83.0  19915.42         0
1   85.0   516.75      56.0  22696.96         0
2   77.0   467.66      86.0  21060.45         0
3  106.0   745.53      81.0   8437.39         1
4   66.0   418.74       1.0  14502.75         0

Informações do DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3214 entries, 0 to 3213
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   calls     3214 non-null   float64
 1   minutes   3214 non-null   float64
 2   messages  3214 non-null   float64
 3   mb_used   3214 non-null   float64
 4   is_ultra  3214 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 125.7 KB

Distribuição da coluna alvo (is_ultra):
Plano Smart (0): 69.35%
Plano Ultra (1): 30.65%

Tamanho dos conjuntos:
Tamanho do conjunto de treino: 1928
Tamanho do conjunto de validação: 643
Tamanho do conjunto de teste: 643

<div class="alert alert-block alert-warning">
Boas adições aqui, especialmente a distribuição das classes. Esta célula agora cobre todo o fluxo de trabalho por si só: imports, carregamento, `info`, a distribuição e uma divisão em treino/validação/teste. As células seguintes repetem os mesmos passos: os dados são carregados novamente, `df.info()` é executado de novo, a distribuição é recalculada e os dados são divididos uma segunda vez. Essa segunda divisão usa `stratify`, enquanto esta não usa, e apenas a divisão posterior alimenta seus modelos. Um leitor não consegue saber facilmente de qual divisão os resultados vêm. Também há anotações esquecidas no código, uma mencionando o "Feedback do revisor" e outra uma "Dica" sobre o caminho do arquivo, que não pertencem a um notebook finalizado. Para um notebook mais limpo, execute cada etapa uma única vez em uma ordem lógica (imports, carregamento, exploração, uma única divisão), exclua as células duplicadas e remova essas anotações. Isso não é um bloqueio, já que seus resultados vêm da divisão correta.
</div>

In [2]:
import pandas as pd

# Carregando os dados do arquivo correto
df = pd.read_csv('users_behavior.csv')

# Exibindo as primeiras linhas para confirmar que funcionou
display(df.head())

# Exibindo informações gerais e o tamanho do dataset
print("\nInformações do DataFrame:")
df.info()

   calls  minutes  messages   mb_used  is_ultra
0   40.0   311.90      83.0  19915.42         0
1   85.0   516.75      56.0  22696.96         0
2   77.0   467.66      86.0  21060.45         0
3  106.0   745.53      81.0   8437.39         1
4   66.0   418.74       1.0  14502.75         0

Informações do DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3214 entries, 0 to 3213
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   calls     3214 non-null   float64
 1   minutes   3214 non-null   float64
 2   messages  3214 non-null   float64
 3   mb_used   3214 non-null   float64
 4   is_ultra  3214 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 125.7 KB

In [2]:
# Verificando a distribuição dos planos (is_ultra)
target_counts = df['is_ultra'].value_counts(normalize=True) * 100
print("Distribuição da coluna alvo (is_ultra) em percentual:")
print(f"Plano Smart (0): {target_counts.get(0, 0):.2f}%")
print(f"Plano Ultra (1): {target_counts.get(1, 0):.2f}%")

Distribuição da coluna alvo (is_ultra) em percentual:
Plano Smart (0): 69.35%
Plano Ultra (1): 30.65%

Análise Exploratória Inicial:

- O dataset possui 3.214 linhas e 5 colunas (calls, minutes, messages, mb_used, is_ultra).
- Uma verificação de valores ausentes confirmou que não há dados nulos no arquivo[cite: 2].
- A coluna alvo (`is_ultra`) mostra a distribuição dos planos: 69.35% dos usuários utilizam o plano Smart (0) e 30.65% utilizam o plano Ultra (1)[cite: 2]. 
- Isso nos fornece uma *baseline* útil de aproximadamente 69.35% de acurácia caso o modelo previsse sempre a classe majoritária.

<div class="alert alert-block alert-warning">
Seu resumo agora está sustentado por resultados reais: a divisão de 69,35% / 30,65% vem do seu próprio cálculo, e o baseline da classe majoritária de cerca de 69,35% é uma boa forma de contextualizar a acurácia dos seus modelos. Dois tópicos ainda contêm artefatos `[cite: 2]` que parecem sobras de copiar e colar. Apague-os para que o texto fique limpo.
</div>

In [4]:
# Separando features e target
features = df.drop(['is_ultra'], axis=1)
target = df['is_ultra']

# 1. Separando 60% para treino e 40% temporário (com stratify para manter a proporção das classes)
features_train, features_temp, target_train, target_temp = train_test_split(
    features, target, test_size=0.4, random_state=54321, stratify=target
)

# 2. Dividindo os 40% temporários igualmente em validação e teste (20% cada)
features_valid, features_test, target_valid, target_test = train_test_split(
    features_temp, target_temp, test_size=0.5, random_state=54321, stratify=target_temp
)

print("Tamanho do conjunto de treino:", len(features_train))
print("Tamanho do conjunto de validação:", len(features_valid))
print("Tamanho do conjunto de teste:", len(features_test))

Tamanho do conjunto de treino: 1928
Tamanho do conjunto de validação: 643
Tamanho do conjunto de teste: 643

<div class="alert alert-block alert-success">
Ótimo trabalho ao usar `stratify` nas duas etapas de divisão. Isso mantém as proporções de Smart/Ultra semelhantes nos três conjuntos, o que é importante quando o alvo é desbalanceado. A divisão 60/20/20 (1928 / 643 / 643) é sensata para cerca de 3.200 linhas, e o `random_state` fixo a torna reproduzível.
</div>

In [5]:
best_tree_model = None
best_tree_acc = 0
best_depth = 0

# Aumentamos o range para testar profundidades até 15
for depth in range(1, 16):
    model = DecisionTreeClassifier(random_state=54321, max_depth=depth)
    model.fit(features_train, target_train)
    predictions = model.predict(features_valid)
    acc = accuracy_score(target_valid, predictions)
    
    if acc > best_tree_acc:
        best_tree_acc = acc
        best_tree_model = model
        best_depth = depth

print(f"Melhor Acurácia (Árvore de Decisão): {best_tree_acc:.4f} com max_depth = {best_depth}")

Melhor Acurácia (Árvore de Decisão): 0.7916 com max_depth = 7

<div class="alert alert-block alert-success">
Bom trabalho ao ampliar o intervalo de `max_depth` para a árvore de decisão. A melhor profundidade (7, acurácia de validação 0.7916) agora está dentro do intervalo, em vez de estar na borda, então a busca é mais convincente. A árvore é selecionada usando apenas a acurácia de validação, que é a abordagem correta.
</div>

In [6]:

best_rf_model = None
best_rf_acc = 0
best_est = 0
best_rf_depth = 0

# Ampliando o leque de n_estimators (até 60) e max_depth (até 15)
for est in range(10, 61, 10):
    for depth in range(1, 16):
        model = RandomForestClassifier(random_state=54321, n_estimators=est, max_depth=depth)
        model.fit(features_train, target_train)
        predictions = model.predict(features_valid)
        acc = accuracy_score(target_valid, predictions)
        
        if acc > best_rf_acc:
            best_rf_acc = acc
            best_rf_model = model
            best_est = est
            best_rf_depth = depth

print(f"Melhor Acurácia (Floresta Aleatória): {best_rf_acc:.4f} com n_estimators = {best_est} e max_depth = {best_rf_depth}")

Melhor Acurácia (Floresta Aleatória): 0.8134 com n_estimators = 30 e max_depth = 14

<div class="alert alert-block alert-success">
Bom trabalho ao estender o grid sobre `n_estimators` e `max_depth` para a random forest. A melhor combinação (`n_estimators = 30`, `max_depth = 14`, acurácia de validação 0,8134) está dentro dos intervalos da sua busca e supera claramente a árvore única. Manter o objeto do melhor modelo para a avaliação final é uma boa prática.
</div>

In [6]:
lr_model = LogisticRegression(random_state=54321)
lr_model.fit(features_train, target_train)
lr_predictions = lr_model.predict(features_valid)
lr_acc = accuracy_score(target_valid, lr_predictions)

print(f"Acurácia (Regressão Logística): {lr_acc:.4f}")

Acurácia (Regressão Logística): 0.6750

<div class="alert alert-block alert-warning">
Você treinou uma regressão logística e verificou sua acurácia na validação (0,6750), o que lhe dá um terceiro tipo de modelo para comparar. Note que esse resultado está abaixo da linha de base de aproximadamente 69,35% que você calculou anteriormente ao sempre prever a classe majoritária, portanto esse modelo não está aprendendo nada útil aqui. Vale a pena mencionar isso na sua conclusão. Como experimento opcional, as features estão em escalas muito diferentes (`mb_used` na casa dos milhares, `calls` na casa das dezenas), então você poderia tentar escalá-las, por exemplo com `StandardScaler`, ou aumentar `max_iter`, para ver se há melhora. Isso não mudaria qual modelo você escolhe.
</div>

In [7]:
# Usando o melhor modelo da Floresta Aleatória para testar
final_test_predictions = best_rf_model.predict(features_test)
final_test_acc = accuracy_score(target_test, final_test_predictions)

print(f"Acurácia Final no Conjunto de Teste: {final_test_acc:.4f}")

Acurácia Final no Conjunto de Teste: 0.8243

<div class="alert alert-block alert-success">
Ótimo trabalho na avaliação final. Você escolheu o random forest usando apenas a acurácia de validação e depois usou o conjunto de teste uma única vez, apenas nesse modelo selecionado, o que evita data leakage (vazamento de dados). A acurácia de teste de 0.8243 está acima do limite de 0.75 e próxima da acurácia de validação (0.8134), então o modelo não parece estar sofrendo de overfitting.
</div>

## Conclusão

Neste projeto, comparamos três modelos de aprendizado de máquina para prever qual plano (Smart ou Ultra) se adequa melhor ao perfil de cada cliente da Megaline: Árvore de Decisão (`DecisionTreeClassifier`), Floresta Aleatória (`RandomForestClassifier`) e Regressão Logística (`LogisticRegression`).

### Resumo dos Resultados de Validação:
- **Árvore de Decisão:** Atingiu uma acurácia de validação de **0.7916** com `max_depth = 7`.
- **Floresta Aleatória:** Apresentou o melhor desempenho geral, alcançando uma acurácia de validação de **0.8134** com `n_estimators = 30` e `max_depth = 14`.
- **Regressão Logística:** Obteve uma acurácia de validação de **0.6750**.

### Avaliação Final no Conjunto de Teste:
O modelo de **Floresta Aleatória**, selecionado por ter apresentado o melhor resultado no conjunto de validação, foi avaliado de forma isolada no conjunto de teste, obtendo uma acurácia final de **0.8243**.

Este resultado supera com folga o limite mínimo exigido de **0.75**, comprovando que o modelo possui excelente capacidade de generalização e é altamente confiável para recomendar o plano ideal aos clientes da Megaline.

<div class="alert alert-block alert-success">
Ótimo trabalho na conclusão. O placeholder foi removido e a acurácia final no teste (0.8243) agora está reportada. Você também apresenta os resultados de validação dos três modelos (0.7916, 0.8134 e 0.6750) e os melhores hiperparâmetros da árvore e da floresta, todos de acordo com as suas saídas. Você explica por que a random forest foi selecionada e que ela foi avaliada uma única vez no conjunto de teste, de modo que o estudo está totalmente descrito.
</div>